apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-katib-mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/c1302bce-0d84-4996-be97-e8205ff1c064/resourceGroups/MC_ResearchSandBox_NlpCluster_westeurope/providers/Microsoft.Compute/disks/diskKatibMysql
    volumeAttributes:
      fsType: ext4